# Include global-theme settings
include=~/.config/global-theme/fuzzel

[main]
font=Adwaita Mono:size=12
line-height=36
image-size-ratio=1
icons-enabled=yes
lines=10
horizontal-pad=40
vertical-pad=20
inner-pad=10
width=50
prompt=""
terminal=foot -e

[border]
width=2
