general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
    ignor_dbus_inhibit = false
}

# Lock
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Monitors off
listener {
    timeout = 630
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# Suspend
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
